version: "3"
services:
  nginx:
    image: nginx:latest 
    restart: always
    ports:
        - "81:80"
    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default
        - ./logs/nginx-error.log:/usr/local/nginx/error.log
        - ./logs/nginx-access.log:/usr/local/nginx/access.log
  phpfpm:
    image: php:7-4-fpm
    restart: always
    ports:
        - "9000:9000"
    volumes:
        - ./public:/usr/share/nginx/html
    links:
     - mysql
  mysql:
    image: mariadb
    environment: #<check var declared in .env file>
      MYSQL_ROOT_PASSWORD: ${root_PW_var} 
      MYSQL_USER: ${user_var} 
      MYSQL_PASSWORD: ${PW_var} 
      MYSQL_DATABASE_PASSWORD: ${db_var} 
    ports:
     - "3306:3306" 
    volumes:
     - ./configs/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - mysql
    ports:
     - 8183:80
    environment: #<check var declared in .env file>
     PMA_USER: ${mysql_user}
     PMA_PASSWORD: ${mysql_user_pw}
     PMA_ARBITRARY: 1